[[section-introduction-and-goals]]
== Introduction and Goals

This document describes the work carried out in the Software Architecture project during the 2020-2021 academic year. The objective is to create an application called Radarin, which is a management system for close friends to your position based on the SOLID architecture. This allows the information to be decentralized and the user can control their information.

Our system is developed by a team of six students from the University of Oviedo who are studying Software Architecture during the 2020-2021 academic year.

This documentation will follow the Arc42 template proposed in class.


=== Requirements Overview

This application's main requirement is to provide a system to see your close friends by accessing the user's location information in a decentralized way; protecting user information. This information will be stored locally for each user.
This project has as high level requirements:

* Users can see their close friends.
* Users will receive notifications whenever a friend is near them.
* Possible close friends may be suggested.

=== Quality Goals

The quality attributes seek to explain non-functional characteristics of the application that are desirable. Radarin quality attributes are:

1. Decentralized: its motivation is to protect user data; privatizing user information.
2. Usable: the application is intuitive; so it should be able to be used by all types of users; both computer experts and novices.
3. Good architecture: develop the application with a good design, keeping the code clean.
4. Testeable: make the application easy to test.
5. Safe: that the application is safe and your information is difficult to access.
6. Distribution: the application architecture must be made up of different elements that communicate with each other.

=== Stakeholders

The following table shows the different users who are interested in our application:
[options="header",cols="1,2,2"]
|===
|Role|Contact|Expectations
| _Sponsor_ | _SOLID team_ | _Comply with the development and functionality of the project using SOLID_
| _Teachers_ | _Teachers_ | _Evaluate that the project requirements are met, teamwork by the development team, etc ..._
| _Users_ | _Potential users of the application_ | _Be able to use an application to see friends close to your position_
| _Development team_ | _Development team_ | _Create a functional application with at least the basic criteria that have been imposed on us_
|===