[[section-introduction-and-goals]]
== Introduction and Goals
Este documento describe el trabajo realizado en el proyecto de Arquitectura del software durante el curso 2020-2021. El objetivo es crear una aplicación llamada Radarin, que es un sistema de gestión de amigos cercanos a tu posición basado en la arquitectura de SOLID. Esto permite que la información sea descentralizada y que el usuario pueda controlar su información.

Nuestro sistema está desarrollado por un equipo de seis estudiantes de la Universidad de Oviedo que están cursando Arquitectura del software durante el curso de 2020-2021.

Esta documentación seguirá la plantilla Arc42 propuesta en clase.


[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview

Esta aplicación tiene como requisito principal proporcionar un sistema para ver tus amigos cercanos accediendo a información de localización del usuario de forma descentralizada; protegiendo la información del usuario. Esta información se almacenará de forma local para cada usuario.
Este proyecto tiene como requisitos de alto nivel:

* Los usuarios pueden ver sus amigos cercanos.
* Los usuarios recibirán notificaciones cada vez que un amigo se encuentre cerca de él.
* Se podrán sugerir posibles amigos cercanos.

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

Los atributos de calidad buscan explicar características no funcionales de la aplicación que son deseables. Los atributos de calidad de Radarin son:

1. Descentralizada: tiene como motivación el proteger los datos de los usuarios; privatizando la información de los usuarios.
2. Usable: la aplicación sea intuitiva; con lo que debería poder ser usada por todo tipo de usuarios; tanto expertos informáticos como noveles.
3. Buena arquitectura: desarrollar la aplicación con un buen diseño, manteniendo el código limpio.
4. Testeable: que la aplicación sea fácil de probar.
5. Segura: que la aplicación sea segura y su información sea difícilmente accesible.
6. Distribución: la arquitectura de aplicación debe estar compuesta por distintos elementos comunicados entre sí.

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
En la siguiente tabla se muestran los distintos usuarios que están interesados en nuestra aplicación:
[options="header",cols="1,2,2"]
|===
|Role|Coontacto|Expectativas
| _Patrocinador_ | _Equipo SOLID_ | _Cumplir con el desarrollo y funcionalidad del proyecto utilizando SOLID_
| _Docentes_ | _Profesores_ | _Evaluar que se cumplen los requisitos del proyecto, el trabajo en equipo por parte del equipo de desarrollo, etc..._
| _Usuarios_ | _Usuarios potenciales de la aplicación_ | _Poder utilizar una aplicación para ver amigos cercanos a su posición_
| _Equipo de desarrollo_ | _Equipo de desarrollo_ | _Crear una aplicación funcional al menos con los criterios básicos que nos han sido impuestos_
|===