[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****


This document describes the work carried out in the Software Architecture project during the 2020-2021 academic year. The objective is to create an application called Radarin, which is a management system for close friends to your position based on the SOLID architecture. This allows the information to be decentralized and the user can control their information.

Our system is developed by a team of six students from the University of Oviedo who are studying Software Architecture during the 2020-2021 academic year.

This documentation will follow the Arc42 template proposed in class.


=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

This application's main requirement is to provide a system to see your close friends by accessing the user's location information in a decentralized way; protecting user information. This information will be stored locally for each user.
This project has as high level requirements:

* Users can see their close friends.
* Users will receive notifications whenever a friend is near them.
* Possible close friends may be suggested.

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

The quality attributes seek to explain non-functional characteristics of the application that are desirable. Radarin quality attributes are:

1. Decentralized: its motivation is to protect user data; privatizing user information.
2. Usable: the application is intuitive; so it should be able to be used by all types of users; both computer experts and novices.
3. Good architecture: develop the application with a good design, keeping the code clean.
4. Testeable: make the application easy to test.
5. Safe: that the application is safe and your information is difficult to access.
6. Distribution: the application architecture must be made up of different elements that communicate with each other.

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****
The following table shows the different users who are interested in our application:
[options="header",cols="1,2,2"]
|===
|Role|Contact|Expectations
| _Sponsor_ | _SOLID team_ | _Comply with the development and functionality of the project using SOLID_
| _Teachers_ | _Teachers_ | _Evaluate that the project requirements are met, teamwork by the development team, etc ..._
| _Users_ | _Potential users of the application_ | _Be able to use an application to see friends close to your position_
| _Development team_ | _Development team_ | _Create a functional application with at least the basic criteria that have been imposed on us_
|===