[[section-solution-strategy]]
== Solution Strategy

=== Technology Decisions

To carry out our project we have decided that we will use the following technologies:

1. React:  As described in point 2.1, this JavaScript library will be used to create and design the graphical interfaces.
2. SOLID: he requirements of the course must follow the SOLID principles of decentralization of user information.
3. GitHub: version control tool also required by the course.
4. Node.js: is an open source, cross-platform runtime environment for the server layer based on the JavaScript programming language, asynchronous, with data I / O in an event-driven architecture based on the Google's V8 engine.
5. Docker: it will allow us to automate the deployment of applications within software containers, as well as an additional layer of abstraction and application virtualization automation.
6. API Google Maps: One of the main functions of the app is a map where you can see the location of the user and their friends. For develop that function we use this https://developers.google.com/maps/documentation/javascript/geocoding[API]
7. MongoDB: MongoDB is a source-available cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. We use it to save the locations of the users and so the users' personal information will not be stored centrally
8. Heroku: is a cloud platform as a service (PaaS) supporting several programming languages, and is said to be a polyglot platform as it has features for a developer to build, run and scale applications in a similar manner across most languages. We will use it for launch the whole application
9. Prometheus: Prometheus is a software application used to monitor and send alerts. Time series store data arranged chronologically, measuring variables over time. Uses an HTTP extraction model, with flexible queries and real-time alerts.
10. Grafana: Grafana is the analytics platform for metrics, allowing you to query, visualize, alert and understand data, no matter where it is stored. It allows you to explore, create and share dashboards with your team. For dashboard display and customization, Grafana is the best of all options. It is multi-functional, easy to use, and very flexible.
11. Serverless events: They are events used in a serverless architecture is a software design pattern in which applications are hosted by a third-party service, eliminating the need for the The developer may need to manage the server hardware and software.


=== Considerations

==== Testing

To achieve the quality goals, as many possible test scenarios must be created to verify the correct operation of the application.

==== Organizational
1. To maintain good communication and solve problems in a transparent way and encourage help among the team members, for the different doubts or problems that arise during the development of the project, the _Issues_ section of Github will be used.
2. Separation of tasks into groups divided into front-end and back-end. This will allow us to work in smaller groups on well differentiated tasks between the two groups.
