[[section-concepts]]
== Cross-cutting Concepts

=== Domain model

* Our domain model will have the following entities:

    ** User
    ** Friends
    ** Location
    ** Map

=== User Experience concepts  
The application is intended to connect friends with each other to share their locations in an intuitive way. In order for the user experience to be as satisfactory as possible, we must take special care that it is friendly and accessible to all users.

It is also important that users familiarize themselves with the use of PODs, since these will be unknown to the vast majority of users. So it is important to introduce them to the world of decentralized information in an appealing way.

=== Safety and security concepts

It is a main objective of the application that it is safe for the user. To achieve this, user information is stored in POD's in which only the user and those authorized by the user can access their information, following the SOLID principles promoted in this subject. The application will only use the necessary data at the time of obtaining its location after acceptance by the user.



=== Architecture and design patterns

* In this project we are going to use:
    
    ** Model view controller (MVC)
    ** For persistence the SOLID principles will be followed
    ** React and React Native
    ** Docker