[[section-design-decisions]]
== Design Decisions

This table will increase during the development of our project. This point is related to the point 4 of this documentation.
The design decision are:

=== Decisions

[options="header",cols="2,2,2"]
|===
|Decision and comments|Advantages|Disadvantages
| Application deployed on web|The user will be able to access the same web application from both the computer and the mobile phone|Some browser: Safari or IOS devices, the application does not work
| The language of the documentation will be in English | Internationalization | Need to write in a language we don't control
| Use of React | The official documentation and there are a lot of tutorials online| Use of Google Maps API, complexity of the lenguage 
| Plenty of documentation and the most easy API to obtain the location | Use of Git for control system and GitHub | Keep a backup of the code and work at the same time in the project 
| Some of the members of the group need to get used to work with it| Use of Visual Studio Code as developmet environment | Easy for us to use it 
|===

=== Rejected alternatives

[options="header",cols="1,2"]
|===
|Decision rejected|Reason
|React Native|Difficulties when logging in with solid
|Mobile Web Notification|The library  API Notifications, was not supported by mobile devices
|Here map API| Problems with the key as it had to be updated every so often and worked slowly
|===

=== Mobile App Decision

At the beginning of the course we had decided to create a mobile app using React Native, we started its development with the react native client, which gave us a lot of dependency problems, we could not add almost any component because it gave us incompatibility of versions in some dependencies.

So, after looking for more documentation we decided to switch to react native expo, from the beginning it went quite well, we advanced a lot in a very short time. We already had a functional map in which we obtained and visualized our position, a navigation menu and a functional test of sending notifications.

The problem came when we tried to login with inrupt using its components, it didn't work. We searched the SOLID forums and found a post with exactly our same problem, but far from finding the solution we saw an answer that the authentication component of inrupt was not tested in react native. We tried to look for more examples and documentation but nothing worked.

Finally we had a team meeting in which it was decided to dispense with the mobile app since we could spend the rest of the course testing solutions to this problem and continue where we were. This was the best decision since the web app was already based on a modular base so its adaptation to mobile screens was going to be easier.

To find a trace to this problem go to the following link: https://github.com/Arquisoft/radarin_es6b/issues/26 


All the code of the mobile app is still in the general "movil" branch: https://github.com/Arquisoft/radarin_es6b/tree/movil 

and different tests in the sub-branches of:

    - fernando_movil: https://github.com/Arquisoft/radarin_es6b/tree/fernando_movil

    - cande: https://github.com/Arquisoft/radarin_es6b/tree/cande

    - UO270656: https://github.com/Arquisoft/radarin_es6b/tree/UO270656 


=== Mobile notifications

Once the idea of creating an app for the cell phone was discarded, it was necessary to send notifications from the web app to the cell phone.  The first alternative that was tested was using the Push API, which is still used on PC but was incompatible with mobile browsers.

Searching for documentation we found in firebase the cloud messaging option that explained that both on PC and Android mobiles, in principle it should work. Apart from the fact that the documentation is quite incomplete as it does not explain all the steps to make it work, a test project was made to check its operation and on web it works but on mobile it still fails.

Finally we opted for the only option that we saw viable, which was to display messages on the web screen instead of sending notifications if the app detected that it was a mobile device.

To find a trace to this problem go to the following link: https://github.com/Arquisoft/radarin_es6b/issues/56 

The different tests can be found in the following branches:

    - https://github.com/Arquisoft/radarin_es6b/tree/notificaciones 

    - https://github.com/Arquisoft/radarin_es6b/tree/notificaciones_posibleSolucion 

Auxiliar proyect to test push notification with firebase cloud messaging:

    - https://github.com/FernandoGiganto/prueba-notificaciones-firebase 